/*
Author: XenoPyax
Discord: XenoPyax#5647
File created: 05/27/2020 13:12
*/

package org.xenodev.edj.discordrpc;

public enum RPCImage {

	ADDER, ALLIANCE_CHALLENGER, ALLIANCE_CHIEFTAIN, ALLIANCE_CRUSADER, ANACOND, ASP_EXPLORER, ASP_SCOUT, BELUGA_LINER, COBRA_MK_III, COBRA_MK_IV, DIAMONDBACK_EXPLORER, DIAMONDBACK_SCOUT,
	DOLPHIN, EAGLE, FEDERAL_ASSAULT_SHIP, FEDERAL_CORVETTE, FEDERAL_DROPSHIP, FEDERAL_GUNSHIP, FER_DE_LANCE, HAULER, IMPERIAL_CLIPPER, IMPERIAL_COURIER, IMPERIAL_CUTTER, IMPERIAL_EAGLE,
	KEELBACK, KRAIT_MK_II, KRAIT_PHANTOM, MAMBA, ORCA, PYTHON, SIDEWINDER, TYPE_10, TYPE_6, TYPE_7, TYPE_9, VIPER_MK_III, VIPER_MK_IV, VULTURE, ELITE_DANGEROUS_LOGO;

}